### ISSUE TITLE
Proposal to add integer abs()

### ISSUE THREAD

**Issue by jan-wassenberg** [WebAssembly/simd#176] opened 2020-01-14 09:32 UTC
abs() for integers would be helpful for JPEG XL - we predict pixels from their neighbours and compute the absolute error.

On x86 and [ARM](https://developer.arm.com/docs/ddi0596/e/shared-pseudocode-functions/shared-functionscommon-pseudocode#impl-shared.Abs.1), INT32_MIN etc. are unchanged - negating them leads to the same result.

Without this operation, I think we could do u32x4_min(x, neg(x)), where neg(x) is either ~x + 1 or _mm_sign_epi32(x, something_negative), or whatever wasm_i32x4_neg uses, so about 3 instructions. By contrast, abs() can be a single instruction on x86 (_mm_abs_epi8..32) and ARM (vabsq_s8..32).

Has this been considered/discussed already?

**Comment by Maratyszcza** [comment] 2020-01-20 19:55
There is PR #128 that propose integer absolute value instructions.

**Comment by jan-wassenberg** [comment] 2020-01-20 20:51
Oh, nice! Sorry about the duplication, I only checked for other issues, not PRs.

**Comment by dtig** [comment] 2020-02-18 19:06
Closing as duplicate of #128 which is now merged.

**Closed by dtig** 2020-02-18 19:06 UTC
