### ISSUE TITLE
Add opcodes for extending different size integer signed and unsigned loads 

### ISSUE THREAD

**Issue by rrwinterton** [WebAssembly/simd#83] opened 2019-07-16 21:54 UTC
In a previous issue the instructions for the following instructions were proposed:

u8x8.zload(mem->v128 (u16) )  - load 8 8 bit unsigned integer to 8 16 unsigned integers zero extended
u16x4.zload(mem->v128 (u32) )  - load 4 16 bit unsigned integer to 4 32 unsigned integers zero extended
u32x2.zload(mem->v128 (u64) )  - load 2 32 bit unsigned integer to 2 64 unsigned integers zero extended

and 

i8x8.sload(mem->v128 (i16) )  - load 8 8 bit signed integer to 8 16 signed integers extended
i16x4.sload(mem->v128 (i32) )  - load 4 16 bit signed integer to 4 32 signed integers extended
i32x2.sload(mem->v128 (i64) )  - load 2 32 bit signed integer to 2 64 signed integers extended

We already have proposed for converting between higher precision to lower in register prior to store.  We need an efficient upload opcode instructions similar to what was proposed at: https://github.com/WebAssembly/simd/issues/21

**Comment by tlively** [comment] 2019-07-16 22:21
Is this a duplicate of #28?

**Comment by penzn** [comment] 2019-07-27 00:06
That gets handled by #77 now, I believe

**Closed** 2019-07-27 16:49 UTC
