### ISSUE TITLE
Load and extend natural alignment

### ISSUE THREAD

**Issue by tlively** [WebAssembly/simd#230] opened 2020-05-14 22:17 UTC
LLVM currently emits load and extend instructions with alignment parameters up to 3 (i.e. 8-byte aligned), but V8 is throwing errors saying the expected maximum alignment for `i16x8.load8x8_s` is 0 (i.e. 1-byte alignment). The overview document does not specify either the natural alignment or the maximum, so we should figure out what they should be.

IMO it makes sense for 8-byte alignment to be the natural alignment because these instructions are loading 8 bytes at a time.

**Comment by ngzhian** [comment] 2020-05-14 22:18
This is a bug in v8, I have a patch at https://chromium-review.googlesource.com/c/v8/v8/+/2202721 which I can hopefully get merged soon.

**Comment by Maratyszcza** [comment] 2020-05-15 20:12
IMO the alignment of load-extend should match the alignment of the elements being loaded (i.e. 1 for `i16x8.load8x8_s`).

**Comment by ngzhian** [comment] 2020-05-15 20:46
Hm, I'm not sure what the right semantics here should be:
- one one hand, we are really loading 8 bytes, so the alignment should be 3 (2^3 = 8 byte)
- but, these 8 bytes could be 8 1-byte (in an array), so the alignment should be 0 (2^0 = 1 byte)

**Comment by ngzhian** [comment] 2020-05-15 21:08
I looked a bit at Intels arch manual 12.10.8 Packed Integer Format Conversions (in the section about SSE4.1 instruction set):
"When accessing memory, no alignment is required for any of the instructions unless alignment checking is enabled. In which case, all conversions must be aligned to the width of the memory reference. "
And in our cases, the memory reference is always 64-bit since we are loading 8-bytes.
I'm not sure how this information will translate to Wasm's memarg.

**Comment by tlively** [comment] 2020-05-15 22:21
IIRC, no existing WebAssembly instruction allows overalignment either, so the natural alignment is always the maximum allowed alignment. So if we want to allow 8-byte alignment, it would be most consistent with the rest of WebAssembly to make the natural alignment 8 bytes as well.

**Comment by Maratyszcza** [comment] 2020-05-16 00:34
WebAssembly does 16-byte alignment for 16-byte loads because they are untyped. Intrinsics with typed loads (e.g. ARMv7 NEON) set alignment according to the natural alignment of the loaded type (i.e. `vld1q_f32` would set alignment to 4 bytes, not 16). Load-extend intrinsics in WebAssembly are typed, so would be best if they don't break expectations set by platform-specific intrinsics, and set alignment likewise based on element type.

**Comment by tlively** [comment] 2020-05-16 01:03
For these instructions the type of the loaded value is an 8-byte vector, though. At least in LLVM, the natural alignment of any 8-byte vector is 8 bytes. I see what you mean about `ld1q_f32`, although I can't find a documented assumed alignment for that function. I would personally prefer consistency with the rest of WebAssembly over consistency with native platforms since the alignment hint will not be useful for these instructions anyway.

**Comment by lars-t-hansen** [comment] 2020-06-05 12:57
Currently i'm encountering a load+extend instruction in emscripten-compiled code that uses alignLog2=4 and SpiderMonkey does not like that, since the byte size of the item in memory is 8.

**Comment by tlively** [comment] 2020-06-05 17:12
@lars-t-hansen huh, do you have the source code that came from or is it in the wild? It sounds like I probably missed a small piece of logic in LLVM for fixing overalignment.

**Comment by tlively** [comment] 2020-06-05 20:29
@lars-t-hansen I double check and LLVM's behavior is correct here, so I'm not sure where an alignLog2=4 would come from.

**Comment by lars-t-hansen** [comment] 2020-06-06 17:10
Yeah, it's mysterious.  As I mentioned in the emscripten channel on discord, emcc seems to produce basically garbage when confronted with simd code.  That is, the output from -S is sensible but the .wasm is full of bugs - even wasm-objdump is stymied.  It's possible the problem is local of course but this is straight up emcc -O1 -msimd128 -o test.wasm test.c with trivial C code.  My emscripten is at `latest` or `latest-upstream`, but that didn't seem to matter.  I can provide more details next week, I'd like to get to the bottom of it.

**Comment by tlively** [comment] 2020-06-06 19:28
Are you perhaps using emcc from after the recent opcode renumbering but wasm-objdump from before the renumbering?

**Comment by lars-t-hansen** [comment] 2020-06-06 20:22
I don't think so, I updated and recompiled wabt on Friday (and updated emscripten too, I believe).  Will provide version numbers when I'm back on that system...

**Comment by lars-t-hansen** [comment] 2020-06-08 12:04
My problems were probably the result of a rotten emscripten install; better now.

**Closed** 2020-06-09 00:02 UTC
